### ISSUE TITLE
If we change value in neo4j directly,  can we remain reactivity ?

### ISSUE THREAD

**Issue by wuxianliang** [VeliovGroup/Meteor-Leaderboard-Neo4j#14]
Dear @dr-dimitru 
When I was changing value in Neo4j browser, the front end did not change reactively. In my case, I want to execute python scripts to change data in Neo4j on server, which aims to remain reactivity at same time. Is there a way to achieve such kind of reactivity? And I tried meteor-mysql https://github.com/numtel/meteor-mysql . I changed the value in phpMyadmin, the front end changed reactively. 

At last I want to use meteor-neo4j in this way, 

Front End ------ call method ------> python script ( gensim, panas ) ---------> Neo4j --------> Front End

If we can't right now, is there another way to achieve such kind of functions?

This is the snippet of calling python.
https://bitbucket.org/drushing/themeddlinproject/wiki/Server-side%20Python%20Script%20Execution

Thank you very much!

**Comment by dr-dimitru** [comment]
Hi @wuxianliang ,
As neo4j doesn't have any hooks/watchers/observer - reactivity works only when you change data via Neo4jReactivity package.
The MySQL you have mentioned, redis and mongodb has built-in observers, that's why data was reactivily changed when you've changed the value in phpMyadmin.

Sorry for this inconvenience, but where is no way to watch data changes on neo4j and push it to subscribed channels, as it happens with mysql/redis/mongodb

**Comment by wuxianliang** [comment]
Thank you. I am trying  to archieve somethings like this with python-meteor, which met problems.

**Comment by FranciscoGutierrez** [comment]
Well I just watched a video: http://youtu.be/jkfnr2hxb9Y?t=1m32s and they are creating nodes and the changes spread to the client. This is the repository: https://github.com/kainolophobia/neo4j-livedata

**Comment by dr-dimitru** [comment]
@FranciscoGutierrez neo4j-livedata project is officially dead
Theirs watcher was based on http requests, on which neo4j is based.
Also by the fact they are poll new data - [polling_observe](https://github.com/kainolophobia/neo4j-livedata/blob/master/polling_observe_driver.js) and this isn't look like a good idea
